{
 "title": "Zabbix Technical Metrics",
 "description": "Technical metrics from Zabbix",
 "tags": [
  "zabbix",
  "technical"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "host", "query": "ZabbixHosts" }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "group": { "filter": "Zabbix servers" },
     "host": { "filter": "Zabbix server" },
     "application": { "filter": "CPU" },
     "item": {
      "filter": "Processor load (1 min average per core)"
     }
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "group": { "filter": "Zabbix servers" }, "host": { "filter": "Zabbix server" }, "application": { "filter": "Memory" }, "item": { "filter": "Available memory" } }
   ]
  },
  {
   "title": "Disk Space Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "group": { "filter": "Zabbix servers" }, "host": { "filter": "Zabbix server" }, "application": { "filter": "Filesystems" }, "item": { "filter": "Free disk space on /" } }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "group": { "filter": "Zabbix servers" },
     "host": { "filter": "Zabbix server" },
     "application": { "filter": "Network" },
     "item": {
      "filter": "Network incoming traffic on eth0"
     }
    }
   ]
  }
 ]
}