version: '3.8'

services:
  sso:
    image: ${DOCKER_REGISTRY}/africa-platform/sso:${TAG}
    container_name: sso
    restart: always
    build:
      context: ../
      dockerfile: SSO/Host//Dockerfile
    profiles:
      - development
      - production
    depends_on:
      - postgres
      - redis

  #### Infrastructure
  postgres:
    image: postgres:13-alpine
    container_name: postgres
    ports:
      - 5432:5432
    profiles:
      - development
    volumes:
      - postgres:/var/lib/postgresql/data/

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres:
  redis_data:

networks:
  default:
    driver: bridge
