version: '3.8'

services:
  sso:
    environment:
      "ASPNETCORE_ENVIRONMENT": "Development"
      "ASPNETCORE_URLS": "https://+;http://+"
      "Kestrel:Certificates:Default:Path": "/app/aspnetapp.pfx"
      "Kestrel:Certificates:Default:Password": "123"
      "Kestrel:Certificates:Default:AllowInvalid": "true"
      "EventBus__HostAddress": "amqp://otus:6GccewECzxGJgTh4QYr82D8JUgCxsC5E@rabbitmq:5672"
      "Services__Dialogs": "http://dialogs"
      "Security__EncryptionKey": "iNyEkoVuMRs1YTdOeKzq0GkpB7sCZy9/CqSVvYr9N9rpYc7RrGJS8LjOfVRhewsf"
      "ConnectionStrings__DefaultConnection": "User ID=postgres;Password=postgres;Host=postgres;Port=5432;Database=postgres;Pooling=true;MaxPoolSize=90;"
    ports:
      - "5001:443"
      - "8001:80"

  dialogs:
    environment:
      "ASPNETCORE_ENVIRONMENT": "Development"
      "ASPNETCORE_URLS": "https://+;http://+"
      "Kestrel:Certificates:Default:Path": "/app/aspnetapp.pfx"
      "Kestrel:Certificates:Default:Password": "123"
      "Kestrel:Certificates:Default:AllowInvalid": "true"
      "ConnectionStrings__DefaultConnection": "User ID=postgres;Password=postgres;Host=dialogs-pg;Port=5432;Database=postgres;Pooling=true;MaxPoolSize=90;"
      "RabbitMQ__HostName": "rabbitmq"
      "RabbitMQ__UserName": "otus"
      "RabbitMQ__Password": "6GccewECzxGJgTh4QYr82D8JUgCxsC5E"
      "RabbitMQ__VirtualHost": "/"
      "Security__EncryptionKey": "iNyEkoVuMRs1YTdOeKzq0GkpB7sCZy9/CqSVvYr9N9rpYc7RrGJS8LjOfVRhewsf"
    ports:
      - "5002:443"
      - "8002:80"


  counter:
    environment:
      "ASPNETCORE_ENVIRONMENT": "Development"
      "ASPNETCORE_URLS": "https://+;http://+"
      "Kestrel:Certificates:Default:Path": "/app/aspnetapp.pfx"
      "Kestrel:Certificates:Default:Password": "123"
      "Kestrel:Certificates:Default:AllowInvalid": "true"
      "Services__Dialogs": "http://dialogs"
      "Security__EncryptionKey": "iNyEkoVuMRs1YTdOeKzq0GkpB7sCZy9/CqSVvYr9N9rpYc7RrGJS8LjOfVRhewsf"
      "ConnectionStrings__DefaultConnection": "User ID=postgres;Password=postgres;Host=counter-pg;Port=5432;Database=postgres;Pooling=true;MaxPoolSize=90;"
      "RabbitMQ__HostName": "rabbitmq"
      "RabbitMQ__UserName": "otus"
      "RabbitMQ__Password": "6GccewECzxGJgTh4QYr82D8JUgCxsC5E"
      "RabbitMQ__VirtualHost": "/"
      "ConnectionStrings__Redis": "redis:6379"
    ports:
      - "5003:443"
      - "8003:80"

  post-socket:
    environment:
      "ASPNETCORE_ENVIRONMENT": "Development"
      "Kestrel:Certificates:Default:Path": "/app/aspnetapp.pfx"
      "Kestrel:Certificates:Default:Password": "123"
      "Kestrel:Certificates:Default:AllowInvalid": "true"
      "RabbitMQ__HostName": "rabbitmq"
      "RabbitMQ__UserName": "otus"
      "RabbitMQ__Password": "6GccewECzxGJgTh4QYr82D8JUgCxsC5E"
      "RabbitMQ__VirtualHost": "/"
    ports:
      - "8083:8080"

  postgres:
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  dialogs-pg:
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  counter-pg:
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
