version: '3.8'

services:
  sso:
    environment:
      "ASPNETCORE_ENVIRONMENT": "Development"
      "ASPNETCORE_URLS": "https://+;http://+"
      "Kestrel:Certificates:Default:Path": "/app/aspnetapp.pfx"
      "Kestrel:Certificates:Default:Password": "123"
      "Kestrel:Certificates:Default:AllowInvalid": "true"
      "EventBus__HostAddress": "amqp://otus:6GccewECzxGJgTh4QYr82D8JUgCxsC5E@rabbitmq:5672"
      "Security__EncryptionKey": "iNyEkoVuMRs1YTdOeKzq0GkpB7sCZy9/CqSVvYr9N9rpYc7RrGJS8LjOfVRhewsf"
    ports:
      - "5001:443"
      - "8001:80"

  dialogs:
    environment:
      "ASPNETCORE_ENVIRONMENT": "Development"
      "ASPNETCORE_URLS": "https://+;http://+"
      "Kestrel:Certificates:Default:Path": "/app/aspnetapp.pfx"
      "Kestrel:Certificates:Default:Password": "123"
      "Kestrel:Certificates:Default:AllowInvalid": "true"
      "Database__Shards__0__ShardId": 1
      "Database__Shards__0__ConnectionString": "Host=dialogs-pg-2;Port=5432;Database=postgres;Username=postgres;Password=postgres"
      "Database__Shards__0__IsActive": true
      "Database__Shards__1__ShardId": 2
      "Database__Shards__1__ConnectionString": "Host=dialogs-pg-1;Port=5432;Database=postgres;Username=postgres;Password=postgres"
      "Database__Shards__1__IsActive": true
      "RabbitMQ__HostName": "rabbitmq"
      "RabbitMQ__UserName": "otus"
      "RabbitMQ__Password": "6GccewECzxGJgTh4QYr82D8JUgCxsC5E"
      "RabbitMQ__VirtualHost": "/"
      "Security__EncryptionKey": "iNyEkoVuMRs1YTdOeKzq0GkpB7sCZy9/CqSVvYr9N9rpYc7RrGJS8LjOfVRhewsf"

    ports:
      - "5002:443"
      - "8002:80"

  post-socket:
    environment:
      "ASPNETCORE_ENVIRONMENT": "Development"
      "Kestrel:Certificates:Default:Path": "/app/aspnetapp.pfx"
      "Kestrel:Certificates:Default:Password": "123"
      "Kestrel:Certificates:Default:AllowInvalid": "true"
      "RabbitMQ__HostName": "rabbitmq"
      "RabbitMQ__UserName": "otus"
      "RabbitMQ__Password": "6GccewECzxGJgTh4QYr82D8JUgCxsC5E"
      "RabbitMQ__VirtualHost": "/"
    ports:
      - "8083:8080"

  postgres:
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  dialogs-pg-1:
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  dialogs-pg-2:
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
