version: '3.8'

services:
  sso1:
    environment:
      "ASPNETCORE_ENVIRONMENT": "Development"
      "ASPNETCORE_URLS": "https://+;http://+"
      "Kestrel:Certificates:Default:Path": "/app/aspnetapp.pfx"
      "Kestrel:Certificates:Default:Password": "123"
      "Kestrel:Certificates:Default:AllowInvalid": "true"
      "ConnectionStrings__DefaultConnection": "User ID=postgres;Password=postgres;Host=haproxy;Port=5443;Database=postgres;Pooling=true;"
      "ConnectionStrings__ReadConnection": "User ID=postgres;Password=postgres;Host=haproxy;Port=5442;Database=postgres;Pooling=true;"
    ports:
      - "5004:443"
      - "8004:80"
  sso2:
    environment:
      "ASPNETCORE_ENVIRONMENT": "Development"
      "ASPNETCORE_URLS": "https://+;http://+"
      "Kestrel:Certificates:Default:Path": "/app/aspnetapp.pfx"
      "Kestrel:Certificates:Default:Password": "123"
      "Kestrel:Certificates:Default:AllowInvalid": "true"
      "ConnectionStrings__DefaultConnection": "User ID=postgres;Password=postgres;Host=haproxy;Port=5443;Database=postgres;Pooling=true;"
      "ConnectionStrings__ReadConnection": "User ID=postgres;Password=postgres;Host=haproxy;Port=5442;Database=postgres;Pooling=true;"
    ports:
      - "5002:443"
      - "8002:80"
  sso3:
    environment:
      "ASPNETCORE_ENVIRONMENT": "Development"
      "ASPNETCORE_URLS": "https://+;http://+"
      "Kestrel:Certificates:Default:Path": "/app/aspnetapp.pfx"
      "Kestrel:Certificates:Default:Password": "123"
      "Kestrel:Certificates:Default:AllowInvalid": "true"
      "ConnectionStrings__DefaultConnection": "User ID=postgres;Password=postgres;Host=haproxy;Port=5443;Database=postgres;Pooling=true;"
      "ConnectionStrings__ReadConnection": "User ID=postgres;Password=postgres;Host=haproxy;Port=5442;Database=postgres;Pooling=true;"
    ports:
      - "5003:443"
      - "8003:80"

  postgres:
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  postgres-slave1:
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  postgres-slave2:
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
