global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

scrape_configs:
  - job_name: 'chat-api'
    scheme: http
    static_configs:
      - targets: ['dialogs']
    metrics_path: '/metrics'
    tls_config:
      insecure_skip_verify: true
    scrape_interval: 10s

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
